### ISSUE TITLE
node_modules resolution when using yarn workspaces

### ISSUE THREAD

**Issue by jptissot** [iTwin/itwinjs-core#3506]
**Describe the bug**
We use a custom build of itwin in our solution and recently moved to yarn workspaces. 

When building the code, none of the static assets get included in the output. This is due to the `node_modules` folder being at the root of our codebase and not relative to `process.cwd()`. 

I tried to fix this issue by overriding the `webpackConfig.resolve.modules` array  with `craco` but the CopyBentleyStaticResourcesPlugin` plugin does not use that config key (see this: https://github.com/iTwin/itwinjs-core/blob/6a0d21347be4310ea3876658d0a3def96541e0ff/tools/webpack-core/src/utils/paths.ts).

**To Reproduce**
1. Setup a repository with yarn workspaces, an ITwin build in a subfolder that is part of the yarn workspace.
2. Try to build, the static assets are not copied.

**Expected behavior**
Static assets are copied properly to the output folder.

**Comment by aruniverse** [comment]
Hi,

This is a known issue of the copy-webpack-plugin having trouble traversing symlinks in monorepos. The recommended approach for the time being is to use the [CopyBentleyStaticResourcesPlugin](https://github.com/iTwin/itwinjs-core/blob/master/tools/webpack-core/src/plugins/CopyBentleyStaticResourcesPlugin.ts#L62). You can use this plugin by setting the `DISABLE_NEW_ASSET_COPY` in your `.env` file, [see notes on our changes to react-scripts](https://github.com/imodeljs/create-react-app/blob/imodeljs/packages/react-scripts/README-imodeljs.md). After thats been set, you need to build your app and the static assets will get copied over.

Note, this will be fixed with @bentley/react-scripts@5, see this [commit](https://github.com/imodeljs/create-react-app/pull/67/commits/2e2b1f848278dacc4f926d997a0d3cbc93b954c5) for the fix

**Comment by aruniverse** [comment]
Are you running a build of your app prior to running start? The build command will actually copy the assets over

**Comment by jptissot** [comment]
The issue I think is that `process.cwd()` returns `\src\packages\itwin\` but node_modules are under `\node_modules` at the root of the solution. As soon as I removed the itwin app from yarn workspaces the assets were copied over properly.

**Comment by aruniverse** [comment]
Have you tried setting the `RELATIVE_MODULE_PATH` env var?

https://github.com/imodeljs/create-react-app/blob/imodeljs/packages/react-scripts/config/modules.js#L23

**Comment by jptissot** [comment]
> Have you tried setting the `RELATIVE_MODULE_PATH` env var?
> 
> https://github.com/imodeljs/create-react-app/blob/imodeljs/packages/react-scripts/config/modules.js#L23

I have not tried that. I will give it a shot. Thanks!

**Comment by calebmshafer** [comment]
@jptissot did @aruniverse's suggestion resolve the issue?
