### ISSUE TITLE
Graphical anomalies with classifier hilite

### ISSUE THREAD

**Issue by ovaisa** [iTwin/itwinjs-core#3859]
Our app is using a reality model with an underlying classifier model for classification of equipment.  In some cases, when I select an equipment on the reality model, the selection also shows random lines.  Please see the selected area hi-lighted in blue in the image below:

![Classifier-Selection](https://user-images.githubusercontent.com/83007711/175470673-72b5c3a1-4b26-4ef1-9156-5b1b485524fa.JPG)

I am using a Microstation CAD model as the classifier model, the portion of this model corresponding the the reality model above is below:

![Classifier Model](https://user-images.githubusercontent.com/83007711/175470828-12c6b48d-77e9-4025-8af5-cc76b6a34a0b.JPG)

IMJS_ITWIN_ID=d20678d8-ad8c-4732-a32f-5ec62e2befc0
IMJS_IMODEL_ID=f78835ef-ff39-40e5-87fa-ccc55b0016b6 (contains multiple iModels, the classifier model is called $Classifier-$Elements)

Reality model is in PW ContextShare named 'Central_2', Project name: BSY_UK_COSURV -> Link below:
(https://api.bentley.com/realitydata/624511f7-fa19-4ba3-b25e-63345cf7919c?projectId=d20678d8-ad8c-4732-a32f-5ec62e2befc0')

Can you please guide how I can resolve this issue.

Thank you,

Ovais

**Comment by pmconne** [comment]
@MarcNeely do you have an explanation for this behavior? As far as I can tell all of the classifier elements highlighted in the screenshot are fully closed volumes.

**Comment by MarcNeely** [comment]
Hmmm, I can't really tell from the image what's going on.  Is this new behavior?  Does it happen with any other models?  I'll try to pull this model & take a look at it.

**Comment by ovaisa** [comment]
We started noticing this after an update of 2.x.  As 3.x was close to release at that point, I wanted to wait to see if this would be fixed in 3.x.  This is the only model we are working with, so I can't comment if it happens with other models but there are several other locations/components in this model where this issue occurs.

**Comment by pmconne** [comment]
@markschlosseratbentley @MarcNeely.
@ovaisa do you recall (roughly) which version of 2.x you were using when it worked and which version you upgraded to in which it broke?

**Comment by markschlosseratbentley** [comment]
@ovaisa We have scheduled this item for investigation.  Thanks.

**Comment by pmconne** [comment]
@ovaisa is it possible to provide access to the project to @MarcNeely so that he can investigate?

**Comment by ovaisa** [comment]
Done, access granted to the project and iModel and also the DGN mailed to Marc.

**Comment by MarcNeely** [comment]
OK, I got the dgn model and have access to the project.  I downloaded the bim using imodel-downloader from the following url: https://connect-imodelweb.bentley.com/imodeljs/?projectId=d20678d8-ad8c-4732-a32f-5ec62e2befc0&iModelId=f78835ef-ff39-40e5-87fa-ccc55b0016b6&ChangeSetId=a49bef3a25cbe760560a79b69665993c6b72e013.

Unfortunately what got downloaded appears to be an empty .bim file.  Its size is 1,224KB, but there doesn't appear to be anything in it when bringing it up in display-test-app.  I ran display-performance-analyzer on it & it couldn't find any models in it.

Looking at the project online at the given url, I see the classification models, (the same as what is in the DGN file that you sent me, and the same as what was in the standalone version of the file that Paul downloaded) but not the reality model.  The DGN file does not have a reality model attached to it either.  To debug this I will need a bim file which has the relevant reality model attached.  Clicking on the link above for the PW ContextShare for the reality model gives me the following error:

  {"error":{"code":"Unauthorized","message":"Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API."}}
