### ISSUE TITLE
Widgets that use stateFunc get added to the left panel, even with a different location specified

### ISSUE THREAD

**Issue by ImVeryLost** [iTwin/itwinjs-core#3873]
**Describe the bug**
Widgets that go from hidden to open/closed visibility state always get added to the left panel, even when a different location is specified. If the default state is "closed" or "open", or if the `stateFunc `is not used, the widget gets added to the expected location.

**To Reproduce**

1. Go to the itwin.js sample: https://www.itwinjs.org/sandboxes/iTwinPlatform/Add%20Toolbar%20Button
2. Modify the `InstructionsWidgetProvider `as is shown below.
3. Modify the `ToolbarButtonProvider`, so clicking the "Added Tool" button invokes `InstructionsWidgetProvider.makeWidgetVisible();`
4. Run the code, click the "Added Tool".
5. You will see that the instructions widget appears on the left panel, even if the `InstructionsWidgetProvider.provideWidgets` specifies a different location.
6. If you remove the `defaultState`, `stateFunc `and `syncEventIds` from the widget definition, or use "closed" default state, the widget appears in the expected location

```
export class InstructionsWidgetProvider implements UiItemsProvider {
  public readonly id: string = "ToolbarButtonInstructionsWidgetProvider";
  private static isVisible = false;
  private static visiblityToggledEvent = "visibilitychanged"

  public provideWidgets(_stageId: string, _stageUsage: string, location: StagePanelLocation, _section?: StagePanelSection): ReadonlyArray<AbstractWidgetProps> {
    const widgets: AbstractWidgetProps[] = [];
    if (location === StagePanelLocation.Right && _section === StagePanelSection.Start) {
      widgets.push(
        {
          id: "ToolbarButtonInstructionsWidget",
          label: "Instructions",
          defaultState: WidgetState.Hidden,
          stateFunc: this.getState,
          syncEventIds: [InstructionsWidgetProvider.visiblityToggledEvent],
          getWidgetContent: () => <InstructionsWidget />,
        }
      );
    }
    return widgets;
  }

  public getState () {
    return InstructionsWidgetProvider.isVisible ? WidgetState.Open : WidgetState.Hidden;
  }

  public static makeWidgetVisible() {
    InstructionsWidgetProvider.isVisible = true;
    SyncUiEventDispatcher.dispatchSyncUiEvent(InstructionsWidgetProvider.visiblityToggledEvent)
  }

}
```

**Expected behavior**
Widget should appear in the location that is specified by the provider.

**Screenshots**
![image](https://user-images.githubusercontent.com/61872067/176128049-4c4823f4-7d9d-425a-93b4-85712ffe3e11.png)

**Desktop (please complete the applicable information):**

- Browser: Chrome, Edge
- iTwin.js Version: 3.2.3

**Comment by NancyMcCallB** [comment]
The stateFunc has been a source of confusion for a number of our users. It is a UI 1.0 concept that was not properly marked in the interface as deprecated, though it will be properly marked in the next release. To get this behavior with the UI 2.0 interface, use the method here: https://www.itwinjs.org/sandboxes/NancyMcCall/Hide%20and%20Show%20Widget%20as%20Desired

The behavior you're seeing with the misplaced widget may be related bug for widgets for hiding and showing floating widgets.  It's fixed in this PR: https://github.com/iTwin/itwinjs-core/pull/3834.

If you're interested: when a widget without the "home" docking area properly initialized was set to left-top. This would also happen when you tried to hide and show a floating widget.

If you have any other trouble with this, please let me know!

Nancy

**Comment by ImVeryLost** [comment]
Thank you for the sandbox, the same approach fixed all issues i had with the layout!

Bit off topic - is it known that the sandboxes don't run in Firefox browser anymore? Not a super pressing issue, but might be worth looking into.
![image](https://user-images.githubusercontent.com/61872067/176212860-1fbe3963-fd36-4a81-97b8-1af47a45a8f5.png)

**Comment by NancyMcCallB** [comment]
@Josh-Schifter Do we know about the Firefox issue?
