### ISSUE TITLE
Bot / GH Action to auto cherry pick changelogs 

### ISSUE THREAD

**Issue by aruniverse** [iTwin/itwinjs-core#4056]
Would be nice to be able to comment on a commit like https://github.com/iTwin/itwinjs-core/commit/8c53e677e40ae86cbaf0a31305dd7857ba8c1e7e and have those changelogs be auto cherry picked to master and any other branches needed

**Comment by calebmshafer** [comment]
A while ago I implemented a naive [finalize release GH action](https://github.com/iTwin/itwinjs-core/actions/workflows/finalize-release.yaml) that would handle this sort of cherry-picking based on which release branch it was created on.

There are currently some issues that I ran into pretty quickly with our workflow since it'll need to know if it's the latest minor or major version that it is being created for or the previous one, also if it's a patch that happens while a current release is happening (i.e. if 3.3.0 is still in progress and a 3.2.x patch release is made, the cherry-pick needs to go to both `master` and `release/3.3.x`).

We should definitely take another pass at this and I think @skirby1996 started looking for a bit a couple months ago so maybe he can add what he found and tried.
