### ISSUE TITLE
[eslint] Failed to load plugin '@typescript-eslint' declared in '.eslintrc

### ISSUE THREAD

**Issue by SunilPrasad** [iTwin/itwinjs-core#4236]
**Describe the bug**
Failed to build application when using @itwin/eslint-plugin .

**To Reproduce**

1. Create new react application using create react app ( React 18 version ).
2. Create eslintrc file with required configuration for @itwin/eslint-plugin
3. npm run build
4. failed to build with following error ( [eslint] Failed to load plugin '@typescript-eslint' declared in '.eslintrc » plugin:@itwin/itwinjs-recommended': Class extends value undefined is not a constructor or null )

**Expected behavior**
Build should successful 

**Screenshots**

![image](https://user-images.githubusercontent.com/3064181/188841172-1a5e41be-02ed-48b2-ae69-4ad828e904b2.png)

**Desktop (please complete the applicable information):**

- OS: [windows 10] : 
- Node [14.16.1]
- iTwin.js Version [3.3.3]

**Comment by calebmshafer** [comment]
@SunilPrasad can you try adding `@typescript-eslint@~4.31.0`as a dev dependency? Hopefully that will be a short-term fix and we will look into why that's being required.

**Comment by SunilPrasad** [comment]
@calebmshafer I have installed typescript-eslint (  npm i --save-dev @typescript-eslint/eslint-plugin@4.31.0 ) but still getting the same error message .

**Comment by aruniverse** [comment]
Could you create & share with us a minimal repo where we can reproduce this?
What package manager are you using?
You mentioned, create-react-app (using react 18), were using react-scripts or @bentley/react-scripts?

**Comment by SunilPrasad** [comment]
@aruniverse Please use this repo to reproducer the issue . I am using npm as a package manager .

https://github.com/SunilPrasad/react-demo-itwin

Node version : 14.16.1
NPM version : 6.14.12

**Comment by aruniverse** [comment]
I dont even see a dep on @itwin/eslint-plugin in there, please add it and whatever other config changes you had to make.

**Comment by SunilPrasad** [comment]
@aruniverse  I have update the code . Please verify once.

**Comment by paulius-valiunas** [comment]
@SunilPrasad we don't recommend running eslint as part of react-scripts build, because react-scripts tries to inject its own config into eslint and that almost always results in conflicts.

One other thing we should be clearer about, is that if you want to use our eslint plugin, in most cases you also need to import [this patch](https://www.npmjs.com/package/@rushstack/eslint-patch) to be able to resolve all the 3rd party plugins that we import. Another option is to install them all separately as devDependencies in your project, but I think it's easier to just use the patch.

I forked your repo and fixed the two issues: https://github.com/paulius-valiunas/react-demo-itwin

Let me know if this solution works for you so we can close this issue.

**Comment by SunilPrasad** [comment]
@paulius-valiunas  Thanks for providing the solution , it's working as expected . We can close the bug.
