### ISSUE TITLE
Newly added CJS module in core-frontend breaks ESM-based frontends

### ISSUE THREAD

**Issue by kckst8** [iTwin/itwinjs-core#4650]
**Describe the bug**
The object-storage-azure.js file was added in [this PR](https://github.com/iTwin/itwinjs-core/pull/3507). This is a pure commonjs module. This will fail any application that is using modern build tooling for es modules, such as iTwin Studio and all of the Viewer samples.

**To Reproduce**
1) Pull the latest [iTwin Studio](https://github.com/iTwin/studio) (or [Viewer Sample Typescript,](https://github.com/iTwin/viewer-sample-typescript) which uses esbuild)
2) upgrade deps to the latest itjs (3.4.4 at time of writing)
3) install deps
4) build (pnpm build/npm run build)

**Expected behavior**
Build succeeds

**Screenshots**
Instead, the build fails because it cannot parse a native CJS module:

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/6283674/201432974-18450a82-cc27-49ca-9116-75dc163cdbc2.png">

We should refrain from adding cjs modules directly in core-frontend as we transition to esm and modern build tooling (Vite, esbuild, etc). 

If you can also contribute a fix, we'd absolutely appreciate it!

Check out the contributor guide to get started:

https://github.com/iTwin/itwinjs-core/blob/master/CONTRIBUTING.md

Just let us know you're working on it and we'd be happy to provide advice and feedback.

-->

**Comment by kckst8** [comment]
@paulius-valiunas @ddorando @aruniverse @calebmshafer

**Comment by calebmshafer** [comment]
@kckst8 this probably needs to be on the object-storage package to update as we are just consuming it within core-frontend. However, I agree we should be more careful in the future of the dependencies we take.

[iTwin/object-storage](https://github.com/iTwin/object-storage)

**Comment by kckst8** [comment]
The cjs module is in core-frontend though. Looks like a re-export but I'm not sure why it isn't a Typescript module that is transpiled to both cjs and esm like the rest?

**Comment by paulius-valiunas** [comment]
@kckst8 it's a dynamic import so it has to be ESM even when we're compiling TS into CJS. It's not object-storage's fault, there's nothing special about that package, but `@azure/storage-blob` is a heavy dependency so we had to import it dynamically to avoid inflating the bundle for no reason when someone wants to use an alternative storage provider. Sadly, dynamic imports are simply impossible with CJS because it can't load modules asynchronously.

**Comment by paulius-valiunas** [comment]
Seems like the error message actually comes from rollup not handling missing sourcemaps correctly. This file doesn't have a sourcemap, so it should just ignore it, but instead it tries to parse it as json:
![image](https://user-images.githubusercontent.com/66480813/201629777-da544330-839e-45ce-b3aa-f672f75ae6d5.png)
(taken from rollup.js, try/catch added by me). I'll keep debugging, there might be a workaround.

**Comment by paulius-valiunas** [comment]
Yes, that's something I overlooked, and it can be fixed by adding `export default module.exports` or something similar to the end of the file, but that doesn't solve your error because it still tries to parse that empty string as a sourcemap.

The file still serves its purpose though, because the goal was just to have _an_ ESM import somewhere in the import chain so that it could be a real dynamic import, and the only way to do that is in a pure JS file because TS would transpile it all into CJS.

I'm considering just giving it an empty mappings file with valid JSON structure. Let me know if you know any better way because I'm kinda lost here. Just the fact that we have a CJS build made me jump through so many hoops I don't know which way is up or down anymore.

**Comment by kckst8** [comment]
why would TS transpile it all into cjs? Isn't there dual builds (one for each module type)?
<img width="790" alt="image" src="https://user-images.githubusercontent.com/6283674/201754588-2b53830b-d2c4-4612-be13-4edeaa534f39.png">

**Comment by aruniverse** [comment]
Just to note, i was unable to repro this with the ts viewer using a cospace with the latest (and making sure to build:esm for all frontend/common pkgs)

**Comment by aruniverse** [comment]
[here](https://github.com/iTwin/itwinjs-core/pull/4656) im attempting to fix this. seems to compile (pkgs and e2e tests) fine; stupid flakey tests failing the ci atm

**Comment by kckst8** [comment]
> Just to note, i was unable to repro this with the ts viewer using a cospace with the latest (and making sure to build:esm for all frontend/common pkgs)

interesting. Maybe it is rollup-specific then. I admit I made an assumption when I saw the code. I will test your fix @aruniverse

**Comment by kckst8** [comment]
Got it. This is going to be difficult since any solution is going to be configuration and tooling dependent. I think the real solution is to use moduleresolution: "node16" but we can't force that on consumers. Any discussions about dropping cjs in v4? Now that esm is no longer experimental in our miminum node it seems like a good time for it. 

I'll see if we can workaround this in rollup config for the time being. Perhaps we will just patch. Still, any consumer that is using vite or rollup native will run into this

**Comment by paulius-valiunas** [comment]
We have an issue open for dropping CJS: https://github.com/iTwin/itwinjs-backlog/issues/337
I think that's one of the main things we'll want to do in 4.0 (@calebmshafer correct me if I'm wrong) but it's still unclear when that release is going to happen.

I'd like to reiterate this again, the error in your screenshot has nothing to do with it being a CJS module. I changed it to ESM in my node_modules and still got the same error when building. Once the sourcemap error is fixed, you may or may not have a problem with the CJS export, but that's a different issue.

**Comment by kckst8** [comment]
I guess what I meant was us being able to use dynamic imports in TS without having to worry about working around the require transpilation.
