### ISSUE TITLE
iTwin Exporter for Datasmith: No "Animations" folder when exporting with "combined-meshes" feature

### ISSUE THREAD

**Issue by KBStrt** [iTwin/itwinjs-core#5093]
Hi, I'm having an issue when exporting any models from itwin. I followed all the steps with the combined meshes turned on. However, the animations folder isn't showing as expected. I tried many times with different projects, but none of them is working. I really don't know what to do anymore.

![image](https://user-images.githubusercontent.com/114533085/219750213-b3bae450-4de0-4a19-bc79-013ebe0990d3.png)

**Comment by MichaelBelousov** [comment]
@KBStrt If you are doing an export with the  "combined meshes" option enabled, the `Animations` folder is only generated if necessary, which is when you have transform (things moving) animations. If it's not there, you don't need it, and all animation can be performed by the generated `ScheduleActor`. You don't need to synchronize with a level sequence because there is no level sequence. Please let me know if you believe there are transform animations and you're not getting an `Animations` folder anyway.

This is described in the [iTwin Exporter for Datasmith animation documentation](https://developer.bentley.com/unreal/integration/documentation/#combinedmeshexportanimationsupport). Please let us know if you think it is unclear.
