### ISSUE TITLE
refactor or remove core-frontend http requests apis

### ISSUE THREAD

**Issue by aruniverse** [iTwin/itwinjs-core#5281]
Kill off or refactor [core/frontend/src/request/Request.ts](https://github.com/iTwin/itwinjs-core/blob/master/core/frontend/src/request/Request.ts)

For iTwin.js 3.0 we killed off the bentley/itwin-client pkg which provided some apis to make http requests. There was still some usage left in core-frontend that depended on the request apis so we moved it to be an internal api of core-frontend, and the goal was to eventually get rid of it. Consumers downstream have started to blindly copy whats in the core library, and unnecessarily pulling in deps to make http reqs. 

Our main objective should be to remove the dependency on 
- [superagent](https://github.com/iTwin/itwinjs-core/blob/master/core/frontend/package.json#L107), 
- [qs](https://github.com/iTwin/itwinjs-core/blob/master/core/frontend/package.json#L105),
- [deep-assign](https://github.com/iTwin/itwinjs-core/blob/master/core/frontend/package.json#L103)

In my opinion we could get away with just using the [fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch) api

**Comment by aruniverse** [comment]
@iTwin/mobilesdkadmins looks like this was also copied into core-mobile, [see](https://github.com/iTwin/itwinjs-core/blob/master/core/mobile/src/backend/Request.ts), maybe its still needed there, but might be worth you guys looking at removing this too

**Comment by aruniverse** [comment]
fwiw, i started looking at this a few weeks back, and didnt get a chance to finish
i don't think itll be too bad to wrap up, prob better to start from a new branch tho
https://github.com/iTwin/itwinjs-core/compare/dep-cleanup

**Comment by tcobbs-bentley** [comment]
@aruniverse Neither @toddsouthenbentley nor I have any knowledge of the linked Request.ts code. I have no idea what it does or why it's there. So refactoring to get rid of it or have it not use the other three packages is not something I can provide constructive input on. I'm guessing that Affan or Steve would know.

Having said that, SYNCHRO Field depends on @bentley/itwin-client for its own WSG-based SYNCHRO-only communication. It sounds like this is saying that them doing that is bad, but maybe it's not for their use case. They should probably be consulted, though: @SatyakamKhadilkar @vincasrazmabentley.

**Comment by SatyakamKhadilkar** [comment]
@aruniverse (cc @tcobbs-bentley).
We used iTwin's usage of Request.ts has a model for doing HTTPS requests for talking to other (Bentley) services directly.
The idea was to use similar API design as the I-model hub client. I wrote a think wrapper to make the API similar for accessing other services.

I am okay with its removal since under the hood we just do plain https requests.

**Comment by SatyakamKhadilkar** [comment]
@aruniverse (cc @tcobbs-bentley).
We used iTwin's usage of Request.ts has a model for doing HTTPS requests for talking to other (Bentley) services directly.
The idea was to use similar API design as the I-model hub client. I wrote a think wrapper to make the API similar for accessing other services.

I am okay with its removal since under the hood we just do plain https requests.
