### ISSUE TITLE
Offset polygon without rounds/chamfers

### ISSUE THREAD

**Issue by dassaf4** [iTwin/itwinjs-core#5344]
User wants an offset polygon without rounds/chamfers.

Specific need is in PowerPlatform .Net geomlibs. User is using the .Net wrapper for `CurveVector::AreaOffset`. But there’s a similar function, `CurveVector::CloneOffsetCurvesXY`. Perhaps there is a combination of settings for the input `CurveOffsetOptions` object that will produce the desired offset.

Any PP solution should be ported to imodel-native (same function names) and iTwinjs: `RegionOps.constructPolygonWireXYOffset`, `RegionOps.constructCurveXYOffset`.
```[tasklist]
### Tasks
- [ ] #5570
- [ ] https://github.com/iTwin/imodel-native/pull/312
- [x] PowerPlatform (native and .Net) solution: https://dev.azure.com/bentleycs/PowerPlatform/_git/PPBase/pullrequest/342656
```

**Comment by saeeedtorabi** [comment]
The fix is done

itwin
https://github.com/iTwin/itwinjs-core/pull/5570

imodel-native
https://github.com/iTwin/imodel-native/pull/312

power-platform
https://dev.azure.com/bentleycs/PowerPlatform/_git/PPBase/pullrequest/342656?path=/BentleyGeometryNet/Test/BentleyGeometryNetTests/CurveVectorTests.cs&_a=files
