### ISSUE TITLE
need Unit Converter for both frontend and backend.

### ISSUE THREAD

**Issue by RaphaelVanierBentley** [iTwin/itwinjs-core#5355]
**Is your feature request related to a problem? Please describe.**
I work in the Civil-iTwin project. We currently have a unit converter in the frontend but not in the backend. A unit converter can convert feet to meter per example, miles to km, etc. We are currently working on some coding to implement Stopping Sight Distance and we absolutely need a unit converter in the backend as the base formula are different if we are working in meter or feet and our geometry database are in meters only. 

**Describe the solution you'd like**
A unit converter that would be available in both frontend and backend would be great. Our current frontend unit converter is UnitManager from "@bentley/civil-frontend". Either place it in "@bentley/civil-common" or create another one in "@bentley/civil-backend"

**Describe alternatives you've considered**
We have created our own Unit manager in the back end that uses UnitsProvider. It works, but this isn't ideal long term.

**Additional context**
-

**Comment by a-gagnon** [comment]
@pmconne Let me clarify -- the `UnitManager` from the civil packages is merely a copy of the `BasicUnitsProvider` we took and put into backend code so that we can perform unit conversions.

The fact that everything is in meters on the backend just doesn't work for some calculations such as the sight distance mentioned above. It uses a different set of constants based on the unit system and the result is not the same all conversion factors considered.

I believe most of our use-cases only involve converting meters <==> feet.  Obviously, we can easily solve the problem by writing simple `convertToFeet`, `convertFromFeet` functions, but we were looking for a more generic approach first.

**Comment by pmconne** [comment]
@ColinKerr any plans in this direction?

**Comment by ColinKerr** [comment]
The unit conversion code in itwinjs-core runs on both the frontend and backend.  It hasn't had many users so it's not public yet, if you guys want to use it and give feedback that would be awesome.  

You can see how to use it via the tests (we still need to do a better job of documentation): https://github.com/iTwin/itwinjs-core/tree/master/core/ecschema-metadata/src/test/UnitConversion

The parsing and formatting code can also run on the backend: https://github.com/iTwin/itwinjs-core/tree/master/core/quantity/src/test

**Comment by calebmshafer** [comment]
closing because there is an existing API. @a-gagnon if you find any issues with it please file a new issue for that issue specifically. Thanks!
