### ISSUE TITLE
@itwin/eslint-plugin dependency version mismatch with @bentley/react-scripts

### ISSUE THREAD

**Issue by ValdasSorys** [iTwin/itwinjs-core#5446]
**Describe the bug**
@itwin/eslint-plugin 3.7.3 requires
```
"@typescript-eslint/eslint-plugin": "~4.31.0",
"@typescript-eslint/parser": "~4.31.0",
```

@bentley/react-scripts 5.0.4-> eslint-config-react-app requires
```
"@typescript-eslint/eslint-plugin": "^5.5.0",
"@typescript-eslint/parser": "^5.5.0",
```

This mismatch can cause issues linting when running eslint from vscode or when building.

**To Reproduce**
In your project with @bentley/react-scripts and @itwin/eslint-plugin extend these rulesets in eslint config:
```
"plugin:@itwin/ui",
"react-app"
```
Try to build with eslint enabled.

**Expected behavior**
`eslint` should run without any problems

**Screenshots**
Error when eslint runs in vscode or when building:
`Error: Plugin "@typescript-eslint" was conflicted between ".eslintrc.js » eslint-config-react-app#overrides[0]" and ".eslintrc.js » plugin:@itwin/ui » plugin:@itwin/itwinjs-recommended".`

**Desktop (please complete the applicable information):**

- OS: macOS
- Browser -
- Version -
- iTwin.js Version 3.7.3

**Comment by calebmshafer** [comment]
@paulius-valiunas can you take a look?

**Comment by paulius-valiunas** [comment]
We have always recommended building React apps with linting disabled (`DISABLE_ESLINT_PLUGIN=true`) because CRA toxically enforces its own rules and dependencies, and will inevitably have version conflicts when used with other eslint plugins. ESLint can be ran on its own in a separate step after the build and you lose nothing at all by doing so, but if you insist on running it in one step, it might work better with `@itwin/eslint-plugin@4.0.0` once we release it. With 4.0 we're moving the eslint plugin as well as some other packages out of lockstep with core packages, so you'll be able to use it even if all your other iTwin.js dependencies are at 3.x. You can try the latest dev version to see if it helps (`4.0.0-dev.38`)

**Comment by ValdasSorys** [comment]
Sorry for late response. Using the dev version helped.
