### ISSUE TITLE
Export BatchedTileTreeReference (create) from frontend-tiles

### ISSUE THREAD

**Issue by alarkbentley** [iTwin/itwinjs-core#5685]
OCP is trying to implement support for the new MeshExport API using the frontend-tiles extension.
Problem is that we are creating new TileTreeReferences to be able to attach a custom transform. When doing this ModelState createTileTreeReference the BatchedTileTreeReference is overwritten.

If we export the BatchedTileTreeReference interface (or just the BatchedTileTreeReference.create) we can create this references ourselves which solves this problem.

Need backport to 3.7.x

**Comment by pmconne** [comment]
Copying pictures of code etc from email:
![image](https://github.com/iTwin/itwinjs-core/assets/22944042/5ab1cbca-a1e5-40bb-a73c-0183af0c09a4)

To be clear: you only need to do this because iTwin.js does not (yet) support multiple iModels. Any changes we make will serve as temporary workarounds.

You will need to rework your code more substantially - the snippet you posted is still associated one `TileTreeReference` with each model. For batched tiles, it's one `TileTreeReference` per iModel, representing all the spatial models.

The API surface of @itwin/frontend-tiles is intentionally small. I don't want you duplicating the logic for computing the tileset URL.

Please link to the branch mentioned above.

**Comment by pmconne** [comment]
The constructor of `SpatialViewState` already allocates the tile tree references for the view via `SpatialTileTreeReferences.create`, which goes through the code path to obtain batched tileset if available.
You can iterate the tile tree references via `ViewState.forEachModelTreeRef` (an internal function, fyi).
So I don't think you need any changes from core.

**Comment by alarkbentley** [comment]
_Please link to the branch mentioned above._
https://dev.azure.com/bentleycs/itwin-experience-cities/_git/cityplanner-frontend/pullrequest/346555

_To be clear: you only need to do this because iTwin.js does not (yet) support multiple iModels. Any changes we make will serve as temporary workarounds._
Yes this is clear. Once iTwin.js support multiple iModels natively this code will be obsolete.

_You can iterate the tile tree references via ViewState.forEachModelTreeRef_
This might work but if I'm not mistaken there is a reason why we create new TileTreeReferences. To be able to support multiple instances of the same iModel in the same viewport.

If it is possible to export the BatchedTileTreeReference.create function that would help us for now.

**Comment by pmconne** [comment]
> This might work but if I'm not mistaken there is a reason why we create new TileTreeReferences. To be able to support multiple instances of the same iModel in the same viewport.

I can think of no reason why that would be the case. You are creating a ViewState per IModelConnection, right? Each ViewState has its own set of TileTreeReferences.
Try it?

**Comment by alarkbentley** [comment]
After some testing is looks like the ViewState.forEachModelTreeRef workaround is ok, thanks. We had some issues with the ProxySpatialTileTreeReference as it was not updating correctly in our case. Solved this by ensuring the mesh urls are loaded before SpatialTileTreeReferences.create is called.
