### ISSUE TITLE
Regression in core-geometry (IModelJson.Reader.parse) with 'bcurve'

### ISSUE THREAD

**Issue by a-gagnon** [iTwin/itwinjs-core#6126]
**Describe the bug**
We've noticed a regression when consuming the latest itwinjs-core packages (4.2.0) and found that it's the `IModelJson.Reader.parse` function that only returns 4 out of the 7 primitives that should've been parsed. (`bcurve` fails to parse while it did previously)

This is from our civil profile when consuming itwinjs-core 4.1.x
![image](https://github.com/iTwin/itwinjs-core/assets/3418768/bca42369-67ec-4d12-ac03-92b483b4e86c)

This is the same profile obtained when consuming itwinjs-core 4.2.0
![image](https://github.com/iTwin/itwinjs-core/assets/3418768/c6c9d18b-f53e-45a3-8354-185fc8e23217)

This is a serialized copy of the data to reproduce the issue.
[vtPathWithBSplines.json](https://github.com/iTwin/itwinjs-core/files/13058022/vtPathWithBSplines.json)

Thanks!
Alex

@dassaf4 @saeeedtorabi @simnorm

**Comment by dassaf4** [comment]
Looks like a [recent change](https://github.com/iTwin/imodel-native/commit/66a60d263d216351caefa1989d11e09b227b213f) to IModelJsonWriter.cpp is creating open B-splines with no `closed` field. This is fine elsewhere: "undefined" is understood to be "open". The problem is the unnecessary insistence of the iTwin parser on a defined value for `closed`.

This iTwin fix will need to be backported to earlier supported versions too since this issue confirms such B-spline json data is out there.

**Comment by a-gagnon** [comment]
Thanks David!
