### ISSUE TITLE
YawPitchRollAngles.createFromMatrix3d method returns undefined

### ISSUE THREAD

**Issue by dovydasjaru** [iTwin/itwinjs-core#6358]
**Bug description**
 When running ```YawPitchRollAngles.createFromMatrix3d``` method with a 3d Matrix described below, a returned value is undefined.
[[0.37146947416490494,        7.033246428758867e-16,        -0.9284451763712457],
[-0.9284452294022093,          2.813991026819455e-16,        -0.3714694529472999],
[1.9186788483451994e-23,    1.0000000571180345,              7.575294995656733e-16]]

**Expected behavior**
A filled YawPitchRollAngles object.

**Running environment:**
- OS: Windows
- Node.Js version: 18.17.1
- iTwin.js Version: 4.2.4

**Comment by saeeedtorabi** [comment]
David and I investigated this.

As the documentation of `YawPitchRollAngles.createFromMatrix3d` says if input matrix is not rigid the function returns `undefined`

``` 
  /**
   * Attempts to create a YawPitchRollAngles object from a Matrix3d
   * * This conversion fails if the matrix is not rigid (unit rows and columns, and transpose is inverse)
   * * In the failure case the method's return value is `undefined`.
   * * In the failure case, if the optional result was supplied, that result will nonetheless be filled with
   * a set of angles.
   */
```

You can check rigidity of your input matrix by `Matrix3d.isRigid`

The matrix you provided is not rigid so `YawPitchRollAngles.createFromMatrix3d` returns `undefined`. However,  your input is very close to rigid (the difference between input transpose and input inverse is 1e-7 which is larger than our expected tolerance 1e-12).

In these kind of situations you have 2 options:

**(a)** Create a `result` object and pass it to `YawPitchRollAngles.createFromMatrix3d`. The function will fill it for you with YPR angles. 
``` 
let result: YawPitchRollAngles = new YawPitchRollAngles();
const ypr = YawPitchRollAngles.createFromMatrix3d(matrix, result);
```
When the method returns `undefined`, you can still use the angles returned in `result`, but with caution. If your input is close to being rigid, then these angles will likely be sufficient. To clarify that when return is defined, it is perfectly fine to trust the angles. And when `undefined`, when they are likely to still be useful.

For your input it's pretty accurate because as I said your input is almost rigid. In fact the angles (radian) it provides are
``` 
yaw: -1.1902051032551855
pitch: 1.918678738754041e-23
roll: 1.570796326794896
```
which later you will see are pretty accurate.

**(b)** If `undefined` is returned, call ` Matrix3d.createRigidFromMatrix3d` or `Matrix3d.makeRigid` and try again.
``` 
const rigidMatrix = Matrix3d.createRigidFromMatrix3d(matrix);
const ypr = YawPitchRollAngles.createFromMatrix3d(rigidMatrix);
```
or
```
matrix.makeRigid();
const ypr = YawPitchRollAngles.createFromMatrix3d(matrix);
```

For your input, if you make either of these calls, your original input is adjusted to be a rigid matrix. The adjustment in your case is only 1e-8 to make your input rigid within our 1e-12 tolerance.

The angles (radian) returned for the adjusted matrix are almost same as the angles we found above:
``` 
yaw: -1.1902051032551855
pitch: 1.9186787387540413e-23
roll: 1.570796326794896
```

We will update the docs to clear this more.

**Comment by dassaf4** [comment]
As @saeeedtorabi found, the angles computed for the near-rigid matrix `m` are almost identical to the angles computed for `m.makeRigid()`.  This begs the question, "Why not return those angles instead of `undefined` in the near-rigid case?" We are looking into this. Specifically, the sanity check at the end of `YawPitchRollAngles.createFromMatrix3d` is applying a tolerance one million times tighter than used elsewhere for comparing general `Matrix3d`s. This tol can likely be loosened to the usual micrometer tolerance, in which case the method will return angles for `m`. We are looking into the ramifications.

**Comment by saeeedtorabi** [comment]
The PR is merged. It means in the next release that includes this PR, `YawPitchRollAngles.createFromMatrix3d` will not return `undefined` for your near-rigid matrix and instead will return YPR angles. For now, you can use the work around by passing `reults` to `YawPitchRollAngles.createFromMatrix3d` or call `Matrix3d.createRigidFromMatrix3d` on your near-rigid matrix.
