### ISSUE TITLE
Exception when setting unit system to US Survey - missing CUB_US_SURVEY_FT

### ISSUE THREAD

**Issue by wilmaier** [iTwin/itwinjs-core#6666]
When setting the unit system to US Survey in pineapple viewer, we see an uncaught exception:

![image](https://github.com/iTwin/itwinjs-core/assets/48260215/0ffb9820-1416-41c1-bc52-7fc421c32077)

1. Open following iModel (likely happens for any iModel):
https://qa-review-eus.itwin.bentley.com/context/8b3d0653-02b5-4a76-832e-7c16ed50ff21/imodel/b9bf7a2d-bf2e-4d3f-b127-90c8029a855e?changesetid=308791f67a9c5ece81a1c792b3ab3cf1ab584b47&it3mode

2. Open Settings dialog and under General Tab select Unit System US Survey

3. Notice in DevTools console an exception is shown

4. The Model tree is no longer display in the Models widget

- iTwin.js Version 4.5.1

**Comment by wilmaier** [comment]
This is a blocking issue for the upcoming pineapple release

**Comment by grigasp** [comment]
@ColinKerr

**Comment by ColinKerr** [comment]
the US Survey volumes were added in Units 1.0.7: https://github.com/iTwin/bis-schemas/blob/fac8b94583872514c97cc2e4aabbe425e4af39e4/SchemaInventory.json#L298

This iModel has units 1.0.4.

Units 1.0.7 was added about 3 years ago which is around the same time the format  using CUB_US_SURVEY_FT was added to the default formats: https://github.com/iTwin/itwinjs-core/blob/fd427e43f7e34263b16b80365b6143aff37348d1/core/frontend/src/quantity-formatting/QuantityFormatter.ts#L1242

The code needs to either check schema version before creating this formatter or needs to wrap in a try/catch.  Remember very old iModels will not even have a units schema because units were hard coded in EC 3.1 ECDb profile 4.0.0.1.  

There are several code paths in addition to the one in the stack above that get the default format for a unit system then load it.  We could handle in `loadFormatAndParserSpec` but that would leave us with no format, maybe the correct answer is to fall back on the hard coded unit system that is used if we find an iModel that has a 4.0.0.1 ECDb profile and has no units schema at all.

**Comment by hl662** [comment]
@wilmaier its been a while since this issue has been raised. I am curious if this is reproducible now? 

For context and a refresher, the root cause of this was the iModel in question did not have a newer version of the units-schema(1.0.4 vs 1.0.7 back then. We are at 1.0.9 right now)

This led to the viewer missing CUB_US_SURVEY_FT, and throwing an error. However, as of iTwin.js 5.9, we've replaced the unitProvider in core-frontend's QuantityFormatter, to default to [this](https://www.itwinjs.org/changehistory/5.9.0/#basicunitsprovider-and-createunitsprovider) new unitsProvider that will always stay in tune with the latest units version. This means unit data by default no longer **needs** to go through an iModel's schema, and this issue should not appear anymore. Last month we had a colleague from your team test out 5.9 changes regarding quantity formatting and the units provider and nothing was flagged.

Is it safe for me to close this out as solved?

**Comment by wilmaier** [comment]
I am still seeing the error when I run pineapple in a localhost build on master:  

<img width="622" height="160" alt="Image" src="https://github.com/user-attachments/assets/b5b43419-6408-4d96-9f27-7c445234503d" />

The current version of twin/core-frontend is 5.10.1

**Comment by hl662** [comment]
Thanks for the reply, I digged into pineapple repo and triaged what's going on, I didn't realize you guys register a bare SchemaUnitProvider. Heres a report from my bot, I think this is the right suggestion and I'd love it if you guys can try it out and fix in on your side:

### My bot's report
After digging deeper, the 5.9 `BasicUnitsProvider` fix is bypassed in pineapple. On every iModel open, `FindSimilarModule` registers a bare `SchemaUnitProvider` as the global units provider via `IModelApp.quantityFormatter.setUnitsProvider`. That provider resolves units from the iModel's backend schema ‚so on an iModel with `Units 1.0.4`, `CUB_US_SURVEY_FT` (added in 1.0.7) isn't found, and switching to US Survey fails.

The 5.9 fix introduced `createUnitsProvider({ primary: SchemaUnitProvider })` from `@itwin/core-quantity` ‚ a composite that consults the schema first and falls back to the bundled BIS units for anything the schema doesn't have. `FindSimilarModule` was using a bare `new SchemaUnitProvider(...)` with no fallback, which is the wrong pattern since 5.9.

Fix is in `FindSimilarModule`: wrap the provider with `createUnitsProvider`:

```typescript
// before
return new SchemaUnitProvider(new ECSchemaRpcLocater(iModel.getRpcProps()));

// after
return createUnitsProvider({ primary: new SchemaUnitProvider(new ECSchemaRpcLocater(iModel.getRpcProps())) });
```

**Comment by wilmaier** [comment]
Thanks Nam.  I have pushed the PR with this change

**Comment by hl662** [comment]
The PR in the relevant downstream repo has been merged, closing this
