### ISSUE TITLE
Documentation Issue: Bad "How to create a Subject" Link

### ISSUE THREAD

**Issue by simihartstein** [iTwin/itwinjs-core#6736]
Link isn't in proper markdown format so is not clickable
![image](https://github.com/iTwin/itwinjs-core/assets/6485888/65a8d4f1-f212-48ab-9946-bcdef0dc07f7)

Found on page https://www.itwinjs.org/reference/core-backend/elements/subject - "undefined"

**Comment by ben-polinsky** [comment]
It's a cruel trick.

That link goes here: https://www.itwinjs.org/learning/backend/createelements/#subject
Which reads: 
`See [Subject.insert](https://www.itwinjs.org/reference/core-backend/elements/subject/#insert)`

And so on... 

Do you think further explanation would be helpful?  Otherwise we should remove the link.

**Comment by simihartstein** [comment]
Not sure I understand. To me, it looks like a typo in the md. The '$' should be after the '('
\[how to create a Subject element]($docs/learning/backend/CreateElements.md#Subject)

Btw, thanks for addressing all of these so quickly 🙂

**Comment by ben-polinsky** [comment]
Ah, yes the link is broken. But I meant that even if the link (on page A) was fixed, it would link to documentation (on page B) which links back to original link's page (page A).

**Comment by simihartstein** [comment]
I see what you're saying. I don't think it's too confusing. They'll figure it out eventually: https://www.reddit.com/r/gifs/comments/3co4ko/wrong_side/
